version: '3.9'

services:
  coupon_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=config.yaml
    volumes:
      - ./config.yaml:/root/config.yaml
